name: Build

on: [push]

jobs:
  build:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v2
    - name: Cache references
      uses: actions/cache@v2
      with:
        path: ~/cache
        key: ${{ runner.os }}-${{ hashFiles('**/lockfiles') }}
    - name: Build figures
      run: make all
    - name: Upload files
      uses: actions/upload-artifact@v2
      with:
        name: files
        path: ./*.pdf
